### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Ibotmealot** [weaves7/ClaimFly#1]
`[15:03:54 ERROR]: Could not pass event PlayerToggleFlightEvent to ClaimFly v1.2.7
java.lang.NoSuchFieldError: BARRIER
        at org.makershaven.claimfly.FlightBoundary.showFlightBoundaries(FlightBoundary.java:41) ~[ClaimFly-1.2.7.jar:?]
        at org.makershaven.claimfly.FlightCheck.check(FlightCheck.java:43) ~[ClaimFly-1.2.7.jar:?]
        at org.makershaven.claimfly.FlightToggleListener.onFlightToggle(FlightToggleListener.java:32) ~[ClaimFly-1.2.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor248.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAbilities(ServerGamePacketListenerImpl.java:3478) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerAbilitiesPacket.handle(ServerboundPlayerAbilitiesPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerAbilitiesPacket.a(ServerboundPlayerAbilitiesPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:03:54 WARN]: [ClaimFly] Task #67 for ClaimFly v1.2.7 generated an exception
java.lang.NoSuchFieldError: BARRIER
        at org.makershaven.claimfly.FlightBoundary.showFlightBoundaries(FlightBoundary.java:41) ~[ClaimFly-1.2.7.jar:?]
        at org.makershaven.claimfly.FlightCheck.check(FlightCheck.java:43) ~[ClaimFly-1.2.7.jar:?]
        at org.makershaven.claimfly.CheckFlyingPlayersTask.checkFlyingPlayers(CheckFlyingPlayersTask.java:28) ~[ClaimFly-1.2.7.jar:?]
        at org.makershaven.claimfly.CheckFlyingPlayersTask.run(CheckFlyingPlayersTask.java:21) ~[ClaimFly-1.2.7.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`
 This is a great plugin, and seems to be working but my console is just full of these errors when using it. I noticed that there hasn't been any updates to this project in some time, but I hope that this is something that can be fixed.

**Comment by weaves7** [comment]
Sorry for the late reply. Not sure how I missed this. Try this build https://github.com/weaves7/ClaimFly/releases/tag/v1.3.0
